batch_size: 64
buffer_size: 64
entropy_coef: 0.04
epochs: 10
eps_clip: 0.08
gnn_dim: 448
grad_norm_clip: 1.0
h_dim: 448
lr: 0.0008
n_layers: 0
q_nstep: 10
residual_gat: true
standardise_returns: false
target_update_interval_or_tau: 0.04
