batch_size: 128
buffer_size: 128
entropy_coef: 0.02
epochs: 10
eps_clip: 0.105
grad_norm_clip: 0.5
h_dim: 320
lr: 0.001
mem_dim: 128
n_layers: 2
q_nstep: 15
standardise_returns: false
target_update_interval_or_tau: 0.04
