batch_size: 128
buffer_size: 128
entropy_coef: 0.02
epochs: 15
eps_clip: 0.175
gnn_dim: 64
grad_norm_clip: 0.5
h_dim: 64
lr: 0.0008
n_layers: 2
q_nstep: 10
skipfeats: True
standardise_returns: False
target_update_interval_or_tau: 0.04