action_selector: soft_policies
add_value_last_step: true
agent: mlp
agent_output_type: pi_logits
batch_size: 8
batch_size_run: 10
buffer_cpu_only: false
buffer_size: 10
checkpoint_path: ''
comm_range: 0.5
common_reward: true
critic_type: cv_critic
device: cuda
entropy_coef: 0.01
env: gymma
env_args:
    dynamic_rescaling: true
    key: mpe2-simple-tag-v3
    max_cycles: 50
    num_adversaries: 10
    num_good: 3
    num_obstacles: 0
    observation_range: 0.25
    pretrained_wrapper: null
    render_mode: rgb_array
    seed: 0
    time_limit: 100
    visual_comm_range: 0.5
epochs: 10
eps_clip: 0.06333268775321842
evaluate: false
gamma: 0.99
grad_norm_clip: 5
hidden_dim: 128
hp_search: 5
hypergroup: null
label: default_label
layer_norm: false
learner: ppo_learner
learner_log_interval: 10000
load_step: 0
local_results_path: results
log_interval: 50000
lr: 0.0004833180632488466
mac: basic_mac
mask_before_softmax: true
n_layers: 4
name: mappo
obs_agent_id: false
obs_individual_obs: false
obs_last_action: false
optim_alpha: 0.99
optim_eps: 5.0e-05
q_nstep: 20
render: false
repeat_id: 1
reward_scalarisation: sum
runner: parallel
runner_log_interval: 10000
save_model: true
save_model_interval: 1000000
save_replay: false
seed: 0
standardise_returns: true
standardise_rewards: true
t_max: 2050000
target_update_interval_or_tau: 0.01
tau: 0.05
test_greedy: true
test_interval: 50000
test_nepisode: 100
unique_token: mappo_seed0_mpe2-simple-tag-v3_2026-04-07 16:41:56.806653
use_cuda: true
use_tensorboard: false
use_wandb: true
wandb_mode: online
wandb_project: epymarl6
wandb_save_model: false
wandb_team: valentincuzin-ucbl1
