batch_size: 96
buffer_size: 96
entropy_coef: 0.01
epochs: 10
eps_clip: 0.2
grad_norm_clip: 0.2
h_dim: 64
lr: 0.0007000000000000001
q_nstep: 5
standardise_returns: false
target_update_interval_or_tau: 0.08
