action_selector: epsilon_greedy
add_value_last_step: true
agent: mlp
agent_output_type: q
batch_size: 32
buffer_cpu_only: false
buffer_size: 32
checkpoint_path: ''
common_reward: true
device: cuda
double_q: true
env: gymma
env_args:
    dynamic_rescaling: true
    key: mpe2-simple-tag-v3
    max_cycles: 50
    num_adversaries: 10
    num_good: 3
    num_obstacles: 0
    observation_range: 0.25
    pretrained_wrapper: RandomTag
    render_mode: rgb_array
    seed: 0
    time_limit: 100
epsilon_anneal_time: 50000
epsilon_finish: 0.01815458057302261
epsilon_start: 0.9701572564868849
evaluate: false
evaluation_epsilon: 0.0
gamma: 0.99
grad_norm_clip: 15.0
h_dim: 256
hp_search: 25
hypergroup: null
hypernet_embed: 192
hypernet_layers: 2
label: default_label
layer_norm: false
learner: q_learner
learner_log_interval: 10000
load_step: 0
local_results_path: results
log_interval: 50000
lr: 0.0007823990005221872
mac: basic_mac
mixer: qmix
mixing_embed_dim: 96
n_layers: 3
name: qmix
obs_agent_id: true
obs_individual_obs: false
obs_last_action: false
optim_alpha: 0.99
optim_eps: 5.0e-05
render: false
repeat_id: 1
reward_scalarisation: sum
runner: parallel
runner_log_interval: 10000
save_model: true
save_model_interval: 1000000
save_replay: false
seed: 0
standardise_returns: true
standardise_rewards: true
t_max: 2050000
target_update_interval_or_tau: 150
test_greedy: true
test_interval: 50000
test_nepisode: 96
unique_token: qmix_seed0_mpe2-simple-tag-v3_2026-04-18 04:22:46.355804
use_cuda: true
use_tensorboard: false
use_wandb: true
wandb_mode: online
wandb_project: epymarl_fixed_env
wandb_save_model: false
wandb_team: valentincuzin-ucbl1
