# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size: 8
batch_size: 8

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005
hidden_dim: 128

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use IA2C
agent_output_type: "pi_logits"
learner: "ppo_learnerv2"
entropy_coef: 0.01
standardise_returns: True
standardise_rewards: True
# q_nstep: 5 # not used in this version
critic_type: "cv_critic"
epochs: 10
eps_clip: 0.2

name: "mappov2"
agent: "mlp"
